In [2]:
import pandas as pd
df=pd.read_csv("Test.csv")
df.head(2)

    x   y
0  15  49
1  23  63

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x       15 non-null     int64
 1   y       15 non-null     int64
dtypes: int64(2)
memory usage: 372.0 bytes

In [6]:
df.isna().sum()

x    0
y    0
dtype: int64

In [8]:
print(type(df['x']))
print(type(df['y']))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

In [17]:
x=df.iloc[:,0:1]
y=df.iloc[:,-1]
print(type(x))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [15]:
x.head()

    x
0  15
1  23
2  18
3  23
4  24

In [16]:
y.head()

0    49
1    63
2    58
3    60
4    58
Name: y, dtype: int64

Creating LinearRegression Model

In [18]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x,y)
y_pred=lr.predict(x)
print(y_pred)

[47.45652174 62.60810811 53.13836663 62.60810811 64.5020564  60.71415981
 60.71415981 55.03231492 55.03231492 49.35047004 64.5020564  39.88072855
 64.5020564  49.35047004 62.60810811]

In [19]:
diff=pd.DataFrame({"Actual":y,"Predicted":y_pred})
diff

    Actual  Predicted
0       49  47.456522
1       63  62.608108
2       58  53.138367
3       60  62.608108
4       58  64.502056
5       61  60.714160
6       60  60.714160
7       63  55.032315
8       60  55.032315
9       52  49.350470
10      62  64.502056
11      30  39.880729
12      59  64.502056
13      49  49.350470
14      68  62.608108

In [20]:
print("Coefficient:",lr.coef_)
print("Intercept:",lr.intercept_)

Coefficient: [1.8939483]
Intercept: 19.047297297297284

In [27]:
from sklearn import metrics
print("MAE: ",metrics.mean_absolute_error(y,y_pred))
print("MSE: ",metrics.mean_squared_error(y,y_pred))
print("R2 Score:",metrics.r2_score(y,y_pred))

MAE:  3.7412847630238946
MSE:  22.292068155111636
R2 Score: 0.7088287858527738

In [44]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=2)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(13, 1)
(2, 1)
(13,)
(2,)

In [47]:
x_train

     x
5   22
0   15
9   16
3   23
1   23
10  24
7   19
12  24
2   18
6   22
14  23
13  16
8   19

In [46]:
x_test

     x
11  11
4   24

In [49]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
l={}
for i in range(1,43):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=i)
    lr=LinearRegression()
    lr.fit(x_train,y_train)
    y_pred=lr.predict(x_test)
    l[i]=metrics.mean_absolute_error(y_test,y_pred)
print(min(l.values()))

0.4198834668608953

In [50]:
print(l)  # ex: for random state={1(random state):5.42(mae)}

{1: 5.422475106685635, 2: 10.933393070489842, 3: 8.325590872045638, 4: 4.241935483870968, 5: 0.4198834668608953, 6: 12.130336351875808, 7: 3.0202984038861906, 8: 8.741160220994473, 9: 4.514369933677234, 10: 5.422475106685635, 11: 3.9011379800853483, 12: 5.551344743276303, 13: 7.0847457627118615, 14: 1.4666788055353237, 15: 5.940064794816411, 16: 10.436977299880528, 17: 3.386221701795474, 18: 8.74116022099448, 19: 6.418938835666911, 20: 12.381548974943051, 21: 3.547159504734161, 22: 7.77169274537696, 23: 10.933393070489842, 24: 3.4314912944738865, 25: 3.3847671665351307, 26: 3.9051215917465036, 27: 2.084784254352769, 28: 5.940064794816411, 29: 7.636330140014731, 30: 2.451612903225808, 31: 6.1114591009579975, 32: 8.325590872045652, 33: 0.9664401019541202, 34: 4.241935483870968, 35: 4.708554125662381, 36: 10.436977299880532, 37: 3.0775248933143615, 38: 4.052611657834984, 39: 5.645413870246077, 40: 4.241935483870964, 41: 7.529411764705877, 42: 9.477684346701174}